# Generated by Django 5.1.3 on 2024-11-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gsm', models.BooleanField(default=False)),
                ('umts', models.BooleanField(default=False)),
                ('lte', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
